### ISSUE TITLE
About the connection with Lidar

### ISSUE THREAD

**Issue by JINGJAN** [MobileRoboticsSkoltech/lidar-sync-mimics-gps#1]
Hi!
I am doing some similar work, trying to do time Synchronization between different lidars.
You have introduced your Prerequisites Hardware. However, I don't know, which cable you used to connect the GPS port of the Lidar. If possible could you give me some suggestions? Or do you have some connection image?
Thank you very much!
![power_ethernet_gps_box](https://user-images.githubusercontent.com/38492507/157302143-f64e58d7-3645-4350-95dd-717aa8163147.jpg)
Best regards
Jing

**Comment by Marselka** [comment]
Dear @JINGJAN,

Thank you for your interest to the project.
We simply utilized a usual custom wires to connect it to MCU board. We unscrew the cover of the box and utilized the header with bolts inside the box. The connections there are marked for convenience. So, we didn't use the interface on the side of the box named "GPS". If I remember correctly, only two wires are needed (GND and UART TX->RX)

Keep connected, there are some details that are to be described within this month. 

Best,
Marsel

**Comment by JINGJAN** [comment]
Dear Marselka,

Thank you for your reply and your work! 
If I understand correctly, you directly connect your MCU with the cables inside the interface box(like the below picture). And you use the black cable(GND) and an RX cable right? I have one question, Velodyne lidar needs PPS and NMEA to do time Synchronization, RX could handle the NMEA message, so how could you deal with the PPS signal? 
![image](https://user-images.githubusercontent.com/38492507/158185218-668f54d6-d6c8-49f3-a4d4-6e3ccd589109.png)

Best,
Jing

**Comment by Marselka** [comment]
Dear @JINGJAN ,

Yes, you are absolutely right. GPS RECEIVE in the box must also be connected to MCU PPS output pin.
Let me check exact pin map and I'll update readme and this topic. I need at least 1 day.

Moreover, directly connecting MCU with GPS RECEIVE is also not a way to go since signal inverter (high-to-low and low-to-high) is needed to correctly send NMEA message. I'll also describe this.

Best,
Marsel

**Comment by Marselka** [comment]
Dear @JINGJAN,

Please, check out readme now. There connection diagram and note about signal inverter are added.

Best,
Marsel

**Comment by JINGJAN** [comment]
Dear @Marselka,

Sorry about the late reply.
And thanks again for this work! I will check your update! 

Best,
Jing

**Comment by Marselka** [comment]
For now, I will close the issue.
